name: CI

on:
  pull_request:
    branches: [main]
env:
  SKIP_INSTALL_SIMPLE_GIT_HOOKS: 1

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      - name: Install frontend dependencies
        run: npm ci

      - name: Create dummy .env file
        run: |
          cat > .env << EOF
          VERCEL_OIDC_TOKEN="dummy_token"
          NEXT_PUBLIC_SUPABASE_URL=https://dummy.supabase.co
          NEXT_PUBLIC_SUPABASE_ANON_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.dummy.key
          NEXT_PUBLIC_HOME_URL=https://trykeep.com/capital
          NEWSAPI_KEY=dummy_newsapi_key
          OPENAI_API_KEY=sk-dummy-openai-key
          EOF

      - name: Cache Next.js build
        uses: actions/cache@v3
        with:
          path: |
            ~/.npm
            ${{ github.workspace }}/.next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('**/*.js', '**/*.jsx', '**/*.ts', '**/*.tsx') }}
          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-

      - name: TypeScript check
        run: npx tsc --noEmit

      - name: Check code formatting
        run: npm run format:check

      - name: Lint frontend
        run: npm run lint

      - name: Build frontend
        run: npm run build
